# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Widget_perfil.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(640, 480))
        Form.setMaximumSize(QtCore.QSize(640, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Resources/system_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.bg_perfil = QtWidgets.QLabel(Form)
        self.bg_perfil.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.bg_perfil.setStyleSheet("background-image: url(:/tela_perfil/tela_perfil.png);")
        self.bg_perfil.setText("")
        self.bg_perfil.setObjectName("bg_perfil")
        self.output_nome = QtWidgets.QLineEdit(Form)
        self.output_nome.setGeometry(QtCore.QRect(74, 121, 353, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_nome.setFont(font)
        self.output_nome.setFrame(False)
        self.output_nome.setReadOnly(True)
        self.output_nome.setObjectName("output_nome")
        self.output_email = QtWidgets.QLineEdit(Form)
        self.output_email.setGeometry(QtCore.QRect(270, 84, 353, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_email.setFont(font)
        self.output_email.setFrame(False)
        self.output_email.setReadOnly(True)
        self.output_email.setObjectName("output_email")
        self.output_curso = QtWidgets.QLineEdit(Form)
        self.output_curso.setGeometry(QtCore.QRect(64, 176, 353, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_curso.setFont(font)
        self.output_curso.setFrame(False)
        self.output_curso.setReadOnly(True)
        self.output_curso.setObjectName("output_curso")
        self.output_entidades = QtWidgets.QLineEdit(Form)
        self.output_entidades.setGeometry(QtCore.QRect(194, 218, 427, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_entidades.setFont(font)
        self.output_entidades.setFrame(False)
        self.output_entidades.setReadOnly(True)
        self.output_entidades.setObjectName("output_entidades")
        self.output_colegio = QtWidgets.QLineEdit(Form)
        self.output_colegio.setGeometry(QtCore.QRect(322, 260, 298, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_colegio.setFont(font)
        self.output_colegio.setFrame(False)
        self.output_colegio.setReadOnly(True)
        self.output_colegio.setObjectName("output_colegio")
        self.output_transporte = QtWidgets.QLineEdit(Form)
        self.output_transporte.setGeometry(QtCore.QRect(394, 317, 227, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_transporte.setFont(font)
        self.output_transporte.setFrame(False)
        self.output_transporte.setReadOnly(True)
        self.output_transporte.setObjectName("output_transporte")
        self.output_telefone = QtWidgets.QLineEdit(Form)
        self.output_telefone.setGeometry(QtCore.QRect(81, 259, 151, 22))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_telefone.setFont(font)
        self.output_telefone.setFrame(False)
        self.output_telefone.setReadOnly(True)
        self.output_telefone.setObjectName("output_telefone")
        self.output_bairro = QtWidgets.QLineEdit(Form)
        self.output_bairro.setGeometry(QtCore.QRect(70, 317, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_bairro.setFont(font)
        self.output_bairro.setFrame(False)
        self.output_bairro.setReadOnly(True)
        self.output_bairro.setObjectName("output_bairro")
        self.output_nascimento = QtWidgets.QLineEdit(Form)
        self.output_nascimento.setGeometry(QtCore.QRect(547, 121, 78, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(11)
        self.output_nascimento.setFont(font)
        self.output_nascimento.setFrame(False)
        self.output_nascimento.setReadOnly(True)
        self.output_nascimento.setObjectName("output_nascimento")
        self.output_semestre = QtWidgets.QLineEdit(Form)
        self.output_semestre.setGeometry(QtCore.QRect(519, 177, 104, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_semestre.setFont(font)
        self.output_semestre.setFrame(False)
        self.output_semestre.setReadOnly(True)
        self.output_semestre.setObjectName("output_semestre")
        self.output_snapchat = QtWidgets.QLineEdit(Form)
        self.output_snapchat.setGeometry(QtCore.QRect(504, 375, 118, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_snapchat.setFont(font)
        self.output_snapchat.setFrame(False)
        self.output_snapchat.setReadOnly(True)
        self.output_snapchat.setObjectName("output_snapchat")
        self.output_instagram = QtWidgets.QLineEdit(Form)
        self.output_instagram.setGeometry(QtCore.QRect(323, 376, 123, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_instagram.setFont(font)
        self.output_instagram.setFrame(False)
        self.output_instagram.setReadOnly(True)
        self.output_instagram.setObjectName("output_instagram")
        self.output_facebook = QtWidgets.QLineEdit(Form)
        self.output_facebook.setGeometry(QtCore.QRect(48, 376, 217, 23))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_facebook.setFont(font)
        self.output_facebook.setFrame(False)
        self.output_facebook.setReadOnly(True)
        self.output_facebook.setObjectName("output_facebook")
        self.select_user = QtWidgets.QComboBox(Form)
        self.select_user.setGeometry(QtCore.QRect(76, 84, 121, 22))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.select_user.setFont(font)
        self.select_user.setObjectName("select_user")
        self.botao_voltar_perfiluser = QtWidgets.QCommandLinkButton(Form)
        self.botao_voltar_perfiluser.setGeometry(QtCore.QRect(11, 435, 90, 36))
        self.botao_voltar_perfiluser.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Resources/botaoenviar - 42x42.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_voltar_perfiluser.setIcon(icon1)
        self.botao_voltar_perfiluser.setObjectName("botao_voltar_perfiluser")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Integrator"))

import tela_perfil_rc
